logging:
  level:
    org:
      pringframework:
        security:
          web:
            FilterChainProxy: ERROR

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_b03068003284c7c
    username: bb5e8f75c48a9a
    password: 86290354
  main:
    allow-circular-references: false

  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
